# Learn avanced numpy

## Broadcasting 
make operations on different arrays with differents shapes

## Rules Broadcasting
    - Dimension are aligned from the right
    - A dimension is compatible if:
        - It matches the other array's dimension
        - One of the dimension is 1

In [1]:
import numpy as np

In [3]:
# Array and scalar broadcasting
arr = np.array([1, 2, 3])

matrix = np.array([[1, 2, 3], [4, 5, 6]])
vector = np.array([1, 0, 1])
print(matrix + vector)

[[2 2 4]
 [5 5 7]]


## Aggregation functions

In [6]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(f"Sum: {np.sum(arr)}")
print(f"Mean: {np.mean(arr)}")
print(f"Max: {np.max(arr)}")
print(f"Min: {np.min(arr)}")
print(f"Standard Deviation: {np.std(arr)}")
print(f"Sum along the rows: {np.sum(arr, axis=0)}")
print(f"Sum along the columns: {np.sum(arr, axis=1)}")

Sum: 21
Mean: 3.5
Max: 6
Min: 1
Standard Deviation: 1.707825127659933
Sum along the rows: [5 7 9]
Sum along the columns: [ 6 15]


## Boolean Indexing and Filtrering

In [8]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

event = arr[arr % 2 == 0]
print(f"Even numbers: {event}") 

arr[arr > 3] = 0
print(f"Modified array: {arr}")

Even numbers: [ 2  4  6  8 10]
Modified array: [1 2 3 0 0 0 0 0 0 0]


## Random number generation and settings seeds

In [10]:
random_arr = np.random.rand(3,3)
print(f"Random Array:\n{random_arr}")

Random Array:
[[0.30045645 0.88149333 0.96630924]
 [0.16783095 0.31045002 0.34230386]
 [0.1475192  0.71636059 0.78656802]]


In [11]:
random_int = np.random.randint(0, 10, size=(2,3))
print(f"Random Integer Array:\n{random_int}")

Random Integer Array:
[[6 2 4]
 [8 7 8]]


In [ ]:
np.random.seed(42)
random_arr_2 = np.random.rand(3,3)
print(f"Random Array with Seed:\n{random_arr_2}")

Random Array with Seed:
[[0.37454012 0.95071431 0.73199394]
 [0.59865848 0.15601864 0.15599452]
 [0.05808361 0.86617615 0.60111501]]


# Exercise 1 Broadcasting operations

In [ ]:
matrix = np.arange(1, 10).reshape(3, 3)
vector = np.array([1, 0, -1])
result = matrix + vector
result_mul = matrix * 2
print(f"Vector:\n{vector}")
print(f"Result:\n{result}")
print(f"Result of Element-wise Multiplication:\n{result_mul}")

Vector:
[ 1  0 -1]
Result:
[[2 2 2]
 [5 5 5]
 [8 8 8]]
Result of Element-wise Multiplication:
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


# Exercise 2

In [22]:
dataset = np.random.randint(0, 100, size=(5, 5))
print(f"Dataset:\n{dataset}")
print(f"Mean of the dataset: {np.mean(dataset)}")
print(f"Standard Deviation of the dataset: {np.std(dataset)}")

#Condition
dataset[dataset > 25] = 0
print(f"Modified Dataset:\n{dataset}")
print(f"Mean of the dataset: {np.mean(dataset)}")
print(f"Standard Deviation of the dataset: {np.std(dataset)}")
print(f"Sum of the dataset: {np.sum(dataset)}")



Dataset:
[[94 47 14 71 77]
 [86 61 39 84 79]
 [81 52 23 25 88]
 [59 40 28 14 44]
 [64 88 70  8 87]]
Mean of the dataset: 56.92
Standard Deviation of the dataset: 26.594615996475678
Modified Dataset:
[[ 0  0 14  0  0]
 [ 0  0  0  0  0]
 [ 0  0 23 25  0]
 [ 0  0  0 14  0]
 [ 0  0  0  8  0]]
Mean of the dataset: 3.36
Standard Deviation of the dataset: 7.2876882479974405
Sum of the dataset: 84
