# Numpy learning course

In [3]:
# Import numpy packages
import numpy as np

In [4]:
#Creating array
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [5]:
# Building functions
zeroes = np.zeros((3, 3))
print(zeroes)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [6]:
ones = np.ones((2, 4))
print(ones)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [10]:
# Using range
range_array = np.arange(1, 10, 2)
print(range_array)

[1 3 5 7 9]


In [15]:
# Linkspace
linspace_array = np.linspace(0, 1, 5)
print(linspace_array)

[0.   0.25 0.5  0.75 1.  ]


In [7]:
# Manipulating arrays
arr = np.array([1, 2, 3, 4, 5, 6])
reshape = arr.reshape((2, 3))
print(reshape)

[[1 2 3]
 [4 5 6]]


In [8]:
# Expanded
arr = np.array([1, 2, 3])
expandede = arr[:, np.newaxis]
print(expandede)

[[1]
 [2]
 [3]]


# Array Operations

In [10]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(a + b)
print(a * b)
print(a / b)

[5 7 9]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [14]:
#Mathematical operations
arr = np.array([4, 16, 25])
print(np.sqrt(arr))
print(np.sum(arr))
print(np.mean(arr))
print(np.max(arr))
print(np.min(arr))

[2. 4. 5.]
45
15.0
25
4


# Array indexing, Slicing and Reshaping

In [22]:
# Indexing and slicing
arr = np.array([10, 20, 30, 40, 50, 60])
print(arr[0])
print(arr[-1])
print(arr[1:4])
print(arr[:3])
print(arr[3:5])

#Reshape

reshaped = arr.reshape(2,3)
print(reshaped)

10
60
[20 30 40]
[10 20 30]
[40 50]
[[10 20 30]
 [40 50 60]]


# Exercise 1

In [23]:
a = np.arange(1, 6)
b = np.arange(6, 11)

print(f"Addition: {a + b}")
print(f"Subtraction: {a - b}")
print(f"Multiplication: {a * b}")
print(f"Division: {a / b}")

Addition: [ 7  9 11 13 15]
Subtraction: [-5 -5 -5 -5 -5]
Multiplication: [ 6 14 24 36 50]
Division: [0.16666667 0.28571429 0.375      0.44444444 0.5       ]


# Exercise 2

In [28]:
# Create array 3x3 and perform operations
matrix = np.arange(1, 10).reshape(3, 3)
print(f"Oringinal Matrix:\n{matrix}")

#Transpose
transpose = matrix.T
print(f"Transposed Matrix:\n{transpose}")

another_matrix = np.arange(10, 19).reshape(3, 3)
print(f"Another Matrix:\n{another_matrix}")
print(f"Matrix Addition:\n{matrix + another_matrix}")
print(f"Matrix Multiplication:\n{matrix * another_matrix}")


Oringinal Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Transposed Matrix:
[[1 4 7]
 [2 5 8]
 [3 6 9]]
Another Matrix:
[[10 11 12]
 [13 14 15]
 [16 17 18]]
Matrix Addition:
[[11 13 15]
 [17 19 21]
 [23 25 27]]
Matrix Multiplication:
[[ 10  22  36]
 [ 52  70  90]
 [112 136 162]]


In [34]:
c = np.arange(1,17).reshape(4,4)
print(f"Sum of all elements: {np.sum(c)}")

Sum of all elements: 136


In [38]:
# Exercise
temperatures = np.array([18, 22, 35, 29, 31, 27, 24])
print(f"Normalized Temperatures: {(temperatures - np.min(temperatures)) / (np.max(temperatures) - np.min(temperatures))}")
print(f"The most hot day was: {temperatures[np.argmax(temperatures)]} degrees")
print(f"The day with the hot temperature was: {np.max(temperatures)} degrees")

Normalized Temperatures: [0.         0.23529412 1.         0.64705882 0.76470588 0.52941176
 0.35294118]
The most hot day was: 35 degrees
The day with the hot temperature was: 35 degrees


In [ ]:
arr_4 = np.arange(1, 17).reshape(4, 4)
print(f"Mean of each column: {np.mean(arr_4, axis=0)}")
min = np.min(arr_4)
max = np.max(arr_4)
normalized_arr_4 = (arr_4 - min) / (max - min)
print(f"Normalized Array:\n{normalized_arr_4}")

Mean of each column: [ 7.  8.  9. 10.]
