# Numpy learning course

In [1]:
# Import numpy packages
import numpy as np

In [2]:
#Creating array
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [4]:
# Building functions
zeroes = np.zeros((3, 3))
print(zeroes)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [5]:
ones = np.ones((2, 4))
print(ones)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [10]:
# Using range
range_array = np.arange(1, 10, 2)
print(range_array)

[1 3 5 7 9]


In [15]:
# Linkspace
linspace_array = np.linspace(0, 1, 5)
print(linspace_array)

[0.   0.25 0.5  0.75 1.  ]


In [ ]:
# Manipulating arrays
arr = np.array([1, 2, 3, 4, 5,6])
reshape = arr.reshape((2, 3))
print(reshape)

ValueError: cannot reshape array of size 5 into shape (2,3)